version: '3.9'
services:
  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${TWITTER_DB_USERNAME}
      - POSTGRES_PASSWORD=${TWITTER_DB_PASSWORD}
      - POSTGRES_DB=${TWITTER_DB_NAME}
    ports:
      - '${TWITTER_DB_PORT}:5432'